import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Icon, PillButton } from "../components/ui";
import * as api from "../lib/api";
import * as supabase from "../lib/supabase";
import { useAccount } from "../state/account";
const inputCls="h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-[16px] text-slate-900 outline-none placeholder:text-slate-400 focus:border-[#0b2b22] focus:ring-2 focus:ring-[#c8f169]/60";
export function LoginPage(){ const navigate=useNavigate(); const {me,backendAvailable,refresh}=useAccount(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [mode,setMode]=useState<"login"|"signup">("login"); const [error,setError]=useState<string|null>(null); const [notice,setNotice]=useState<string|null>(null); const [busy,setBusy]=useState(false);
 const submit=async()=>{setError(null);setNotice(null);const e=email.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(e)){setError("Enter a valid email.");return}if(password.length<8){setError("Password must be at least 8 characters.");return}if(mode==="signup"&&password!==confirm){setError("Passwords do not match.");return}setBusy(true);const r=mode==="signup"?await supabase.signUp(e,password):await supabase.signInWithPassword(e,password);if(!r.ok){setBusy(false);setError(r.message);return}if(r.emailConfirmationRequired){setBusy(false);setNotice("Account created. Check your email to confirm it, then log in with your password.");setMode("login");setPassword("");setConfirm("");return}if(!r.accessToken){setBusy(false);setError("Supabase returned no session token. Nothing is faked.");return}const checked=await api.loginCheck(r.accessToken);setBusy(false);if(!checked.ok){setError(checked.error.message??"The server rejected this session.");return}await refresh();navigate("/profile");};
 const reset=async()=>{setError(null);setNotice(null);if(!email.trim()){setError("Enter your email first.");return}setBusy(true);const r=await supabase.resetPasswordForEmail(email.trim());setBusy(false);if(r.ok)setNotice("If that email has a Run Local account, Supabase will send password reset instructions.");else setError(r.message);};
 if(me?.status==="signed_in")return <div className="mx-auto w-full max-w-md px-4 pb-32 pt-6"><div className="rounded-2xl bg-white p-6 text-center shadow-sm ring-1 ring-slate-200/70"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#c8f169] text-[#0b2b22]"><Icon name="check" className="h-7 w-7"/></span><h1 className="mt-3 text-xl font-extrabold">You're signed in</h1><PillButton variant="primary" className="mt-4 w-full" onClick={()=>navigate("/profile")}>Go to my profile</PillButton></div></div>;
 return <div className="mx-auto w-full max-w-md px-4 pb-32 pt-4"><button type="button" onClick={()=>navigate(-1)} className="mb-3 flex items-center gap-1 text-[13px] font-semibold text-slate-500"><Icon name="chevronRight" className="h-4 w-4 rotate-180"/> Back</button>{!backendAvailable&&<p className="mb-4 rounded-xl bg-amber-50 p-3.5 text-[13px] text-amber-900">The Run Local server is unreachable — sign-in is unavailable.</p>}<section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200/70"><h1 className="text-xl font-extrabold">{mode==="login"?"Log in":"Create your account"}</h1><p className="mt-1 text-[13px] text-slate-600">Use your email and password. Your Run Local session is secured by server-side token validation.</p><div className="mt-4 space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-semibold">Email</span><input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className={inputCls}/></label><label className="block"><span className="mb-1.5 block text-sm font-semibold">Password</span><input type="password" autoComplete={mode==="login"?"current-password":"new-password"} value={password} onChange={e=>setPassword(e.target.value)} className={inputCls}/></label>{mode==="signup"&&<label className="block"><span className="mb-1.5 block text-sm font-semibold">Confirm password</span><input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} className={inputCls}/></label>}{error&&<p className="rounded-xl bg-red-50 p-3.5 text-[13px] text-red-800">{error}</p>}{notice&&<p className="rounded-xl bg-emerald-50 p-3.5 text-[13px] text-emerald-900">{notice}</p>}<PillButton variant="primary" className="w-full" disabled={busy} onClick={()=>void submit()}>{busy?(mode==="login"?"Logging in…":"Creating account…"):(mode==="login"?"Log in":"Create account")}</PillButton>{mode==="login"&&<button type="button" disabled={busy} onClick={()=>void reset()} className="block w-full text-center text-sm font-semibold text-[#0b2b22] underline">Forgot password?</button>}<p className="text-center text-xs text-slate-400">{mode==="login"?"New here?":"Already have an account?"}{" "}<button type="button" onClick={()=>{setMode(mode==="login"?"signup":"login");setError(null);setNotice(null)}} className="font-semibold text-[#0b2b22] underline">{mode==="login"?"Create an account":"Log in instead"}</button></p></div></section></div> }
